services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
    - 9990:8080
    command:
    - start-dev
    restart: always