services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "9990:8080"
    restart: always